### ISSUE TITLE
 update assert.ok(!data.age, 'data.age is falsy');

### ISSUE THREAD

**Issue by ivoberg** [feathersjs/databases#13]
can you explain [ assert.ok(!data.age, 'data.age is falsy');](https://github.com/ivoberg/databases/blob/85e1e7a54bacfaabbf9478d0a71d40e710924746/packages/adapter-tests/src/methods.ts#L194)
Update should return whole object and not try to update fields with null

**Comment by daffl** [comment]
`.update` is intended to replace the entire object and either remove all fields that have not been passed or set them to `null` in relational database. `patch` is used for partial updates.

**Comment by ivoberg** [comment]
I believe that if there is validation on model with allowNull : false it doesn't allow for the code of feathers-sequelize to pass.
I have a [PR](https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/355) that does not pass because of this.

**Comment by daffl** [comment]
The PR didn't have a lot of context for what you were trying to do and what didn't work. I'd start with creating an issue in feathers-sequelize with the steps to reproduce and the expected vs actual result.
