### ISSUE TITLE
Add test to ensure results are returned from .patch method when query and data have the same props.

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs/databases#3]
I just recently closed https://github.com/feathersjs-ecosystem/feathers-sequelize/issues/346

As far as I know, there was no test ensuring that the following code returns the proper results
```js
// Notice how we are both querying by the completed as well as updating the completed props
app.service('posts').patch(
  null,
  { completed: true },
  { query: { completed: false } }
)
```

In feathers-sequelize, there were no results returned from the above code snippet, even though records were updated, but all the tests still passed.

**Comment by daffl** [comment]
I thought this would've been covered with https://github.com/feathersjs/databases/blob/master/packages/adapter-tests/src/methods.ts#L343-L369 but you're right, the condition is always true before and after so it really doesn't :|

**Comment by DaddyWarbucks** [comment]
I may be able to dive into this early next week.

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/databases/pull/5
